export default {
    nav:[
        {
            nav_title:'小程序管理',
            index:'1',
            icon:'el-icon-service',
            nav_subs:[
                {
                    index:'1-1',
                    sub_title:'首页',
                    path:'/manager/home'
                },
                {
                    index:'1-2',
                    sub_title:'car',
                    path:'/manager/car'
                },
                {
                    index:'1-3',
                    sub_title:'shop',
                    path:'/manager/shop'
                }
            ]
        },
        {
            nav_title:'商家管理',
            index:'2',
            icon:'el-icon-bell',
            nav_subs:[
                {
                    index:'2-1',
                    sub_title:'home',
                    path:'/system/home'
                },
                {
                    index:'2-2',
                    sub_title:'car',
                    path:'/system/car'
                },
                {
                    index:'2-3',
                    sub_title:'shop',
                    path:'/system/shop'
                }
            ]
        }
    ]
}